apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fastify-cloudflare-chunked-encoding-before
resources:
- ../../base
patches:
- target:
    kind: Ingress
  patch: |
    - op: replace
      path: /spec/rules/0/host
      value: fastify-cloudflare-chunked-encoding-before.example.com
