apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fastify-cloudflare-chunked-encoding-after
resources:
- ../../base
patches:
- target:
    kind: Ingress
  patch: |
    - op: replace
      path: /spec/rules/0/host
      value: fastify-cloudflare-chunked-encoding-after.example.com
    - op: add
      path: /metadata/annotations/cloudflare-tunnel-ingress-controller.strrl.dev~1disable-chunked-encoding
      value: true
